# Generated by Django 6.0.3 on 2026-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('deadline', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('college_id', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=180)),
                ('branch_focus', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('prize_money', models.CharField(blank=True, max_length=80)),
                ('registration_link', models.URLField()),
                ('poster', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('created_by', models.EmailField(default='admin@gmail.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
